name:                 call-coding-clis
version:              0.1.0.0
visibility:           public
id:                   call-coding-clis-0.1.0.0-inplace
key:                  call-coding-clis-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:
    CallCodingClis.PromptSpec CallCodingClis.Runner
    CallCodingClis.Types

import-dirs:
    /home/xertrov/src/call-coding-clis/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/call-coding-clis-0.1.0.0/build

library-dirs:
    /home/xertrov/src/call-coding-clis/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/call-coding-clis-0.1.0.0/build

library-dirs-static:
    /home/xertrov/src/call-coding-clis/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/call-coding-clis-0.1.0.0/build

dynamic-library-dirs:
    /home/xertrov/src/call-coding-clis/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/call-coding-clis-0.1.0.0/build

data-dir:             /home/xertrov/src/call-coding-clis/haskell/.
hs-libraries:         HScall-coding-clis-0.1.0.0-inplace
depends:              base-4.18.3.0 process-1.6.19.0
haddock-interfaces:
    /home/xertrov/src/call-coding-clis/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/call-coding-clis-0.1.0.0/doc/html/call-coding-clis/call-coding-clis.haddock

haddock-html:
    /home/xertrov/src/call-coding-clis/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/call-coding-clis-0.1.0.0/doc/html/call-coding-clis
